import { deflateSync } from 'node:zlib'
import type { Page } from '@playwright/test'

// --- A real PNG, because the thing under test is geometry ---
//
// The fixture's only job is to carry an intrinsic size the browser will believe, so an
// SVG would have been fewer lines. It is a raster PNG anyway: production serves PNGs, and
// an SVG without a viewBox is "scalable" to the layout engine in ways a page image is not.
// Substituting a different intrinsic-sizing model into the one test whose subject *is*
// intrinsic sizing would quietly stop testing the real thing.

const CRC_TABLE = (() => {
  const table = new Int32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    table[n] = c
  }
  return table
})()

function crc32(buf: Buffer): number {
  let c = ~0
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8)
  return ~c >>> 0
}

function chunk(type: string, data: Buffer): Buffer {
  const length = Buffer.alloc(4)
  length.writeUInt32BE(data.length)
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data])
  const crc = Buffer.alloc(4)
  crc.writeUInt32BE(crc32(body))
  return Buffer.concat([length, body, crc])
}

/** A valid 8-bit grayscale PNG of exactly `w` x `h`. Uniform white; it is never looked at. */
export function png(w: number, h: number): Buffer {
  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(w, 0)
  ihdr.writeUInt32BE(h, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 0 // colour type: grayscale
  // bytes 10-12 stay 0: compression, filter, interlace
  // Each scanline is a filter byte (0 = None) followed by one byte per pixel.
  const raw = Buffer.alloc((w + 1) * h, 0xff)
  for (let y = 0; y < h; y++) raw[y * (w + 1)] = 0
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

// --- A real PDF, for the same reason the PNG above is a real raster ---
//
// The viewer's subject is now the document itself, so the fixture has to be one: a stub
// that pdf.js cannot parse would fall straight through to the PNG path and the suite would
// pass while testing the branch it is supposed to have replaced.
//
// Hand-written rather than generated by a library, because it is ~30 lines and the only
// hard part is that the xref table holds byte offsets, so the file has to be assembled
// before it can be indexed. `/BaseFont /Helvetica` with no embedded font file is
// deliberate: it exercises the standard-font data that vite.config.ts copies into
// assets/pdfjs/, so a build that failed to emit it fails a test rather than a reader.

/** The string drawn on every page, so a test can assert the text layer really extracted it. */
export const PDF_TEXT = 'Vision RAG fixture page'

/** A valid `pages`-page PDF, each page `w` x `h` points, each carrying PDF_TEXT. */
export function pdf(w: number, h: number, pages: number): Buffer {
  // Object 1 catalog, 2 page tree, 3 font, then a page and a content stream per page.
  const pageId = (i: number) => 4 + i * 2
  const bodies: string[] = [
    '<</Type/Catalog/Pages 2 0 R>>',
    `<</Type/Pages/Kids[${Array.from({ length: pages }, (_, i) => `${pageId(i)} 0 R`).join(' ')}]/Count ${pages}>>`,
    '<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
  ]
  for (let i = 0; i < pages; i++) {
    const stream = `BT /F1 24 Tf 40 ${h - 60} Td (${PDF_TEXT} ${i + 1}) Tj ET`
    bodies.push(
      `<</Type/Page/Parent 2 0 R/MediaBox[0 0 ${w} ${h}]` +
        `/Resources<</Font<</F1 3 0 R>>>>/Contents ${pageId(i) + 1} 0 R>>`,
      `<</Length ${stream.length}>>\nstream\n${stream}\nendstream`,
    )
  }

  let out = '%PDF-1.7\n'
  const offsets = bodies.map((body, i) => {
    const at = out.length
    out += `${i + 1} 0 obj\n${body}\nendobj\n`
    return at
  })
  const startxref = out.length
  out += `xref\n0 ${bodies.length + 1}\n0000000000 65535 f \n`
  for (const at of offsets) out += `${String(at).padStart(10, '0')} 00000 n \n`
  out += `trailer\n<</Size ${bodies.length + 1}/Root 1 0 R>>\nstartxref\n${startxref}\n%%EOF\n`
  // latin1: every byte above is ASCII, and this keeps string length == byte length, which
  // is what the offsets recorded above assume.
  return Buffer.from(out, 'latin1')
}

export const PDF = 'fixture.pdf'
export const PAGE_COUNT = 3

/**
 * Stub every endpoint the app touches on the way to the document viewer, serving both the
 * source PDF and the page images at a chosen size.
 *
 * Network-level stubs rather than a live backend on purpose: these tests are about how the
 * browser lays out a page, and standing up ColQwen2 + Qdrant + Gemini in CI to answer that
 * would be several minutes and an API key for a question none of them influence.
 *
 * `source` selects which of the viewer's two render paths is under test:
 *   'ok'      - the PDF is served, so pdf.js renders it (the normal path)
 *   'missing' - `has_original: false`, so the viewer never asks for it
 *   'error'   - claimed present but 404s, the half-corpus state the API names explicitly
 * The last two must both land on the page image, which is why they are separate: one is a
 * decision made from the manifest and the other is a failed fetch.
 */
export async function mockBackend(
  page: Page,
  size: { w: number; h: number },
  source: 'ok' | 'missing' | 'error' = 'ok',
): Promise<void> {
  await page.route('**/health', (route) =>
    route.fulfill({ json: { status: 'ok', model_loaded: true, qdrant: 'ok', corpus: 'ok' } }),
  )
  await page.route('**/corpus', (route) =>
    route.fulfill({
      json: {
        documents: [{ pdf: PDF, page_count: PAGE_COUNT }],
        total_pages: PAGE_COUNT,
        qdrant: 'ok',
      },
    }),
  )
  await page.route('**/corpus/*/pages', (route) =>
    route.fulfill({
      json: {
        pdf: PDF,
        page_count: PAGE_COUNT,
        has_original: source !== 'missing',
        pages: Array.from({ length: PAGE_COUNT }, (_, i) => ({
          page_number: i + 1,
          image: { url: `/images/fixture_page_${i + 1}.png`, data_uri: null },
        })),
      },
    }),
  )
  await page.route('**/corpus/*/file', (route) =>
    source === 'ok'
      ? route.fulfill({ contentType: 'application/pdf', body: pdf(size.w, size.h, PAGE_COUNT) })
      : route.fulfill({ status: 404, json: { detail: `${PDF} is indexed but not on disk.` } }),
  )
  await page.route('**/images/**', (route) =>
    route.fulfill({ contentType: 'image/png', body: png(size.w, size.h) }),
  )
}
